### ISSUE TITLE
Account view very limited

### ISSUE THREAD

**Issue by aaron-horowitz** [aclu-national/civis#2]
Started to work with accounts and the view is very limited. Any reason why? @ndeutsch-7  - are there things you'd want added to this?

https://github.com/aclu-national/civis/blob/a80691909f5824ed1c7e4bfe2a7b985f977cd8bf/salesforce/sql/ddl/create_sf_views.sql#L7

**Comment by CharlieRubin** [comment]
Aaron, you're right - I just saw this. I think it was the very first table I did, and I didn't use the same process I developed later on. I will re-do it, and check the other ones I did early on as well.

**Comment by aaron-horowitz** [comment]
#5 overlaps with this. Will close this request and keep the other one open.
